Add section for Godcr download
planetdecred/website pull request #28
Opened 2022-05-18 21:44 UTC by devchoplife

Closes #27 
This PR adds a sections on the downloads page to download godcr

2022-05-18 21:51 UTC, dreacot requested changes

2022-05-18 21:51 UTC, dreacot commented on layouts/downloads/list.html
> +        <h2 >Decred Wallet For Computers</h2>
A cross-platform desktop [SPV](https://docs.decred.org/wallets/spv/) wallet for [decred](https://decred.org/) built with [gio](https://gioui.org/)

2022-05-18 21:51 UTC, dreacot commented on layouts/downloads/list.html
> +        <a href="https://github.com/planetdecred/godcr/releases" target="_blank">Download GoDCR binaries</a>
![Screenshot from 2022-05-18 22-48-29](https://user-images.githubusercontent.com/25265396/169161516-e961ae3d-ffc0-4ca1-a7a1-ed8881ad20ee.png)

Let's have download buttons for individual platforms, so they can download directly

something like in the picture above

2022-05-18 21:52 UTC, raedah commented
Make sure the fonts sizes are reasonable with good proportions.

2022-05-18 21:52 UTC, raedah commented
Also note vertical spacing between sections.

2022-05-18 21:53 UTC, raedah commented
Mobile buttons can be put side by side since we are adding more to the page.

2022-05-20 11:17 UTC, dreacot commented
> Mobile buttons can be put side by side since we are adding more to the page.

@devchoplife this hasn't been attended to, i believe he is referring to the mobile buttons

2022-05-20 11:20 UTC, dreacot requested changes

2022-05-20 11:20 UTC, dreacot commented on layouts/downloads/list.html
> +            <a class = "add-margin" href="https://github.com/planetdecred/godcr/releases/download/v1.7.0/GoDCR-v1.7.0.dmg" target="_blank">Mac OS ↓ <span style="margin-left: 5px;">|</span></a>
remove the underline when the links are hovered

2022-05-20 15:42 UTC, dreacot approved these changes

2022-05-20 15:45 UTC, dreacot requested changes

2022-05-20 15:45 UTC, dreacot commented on layouts/downloads/list.html
> +        <h2 >GoDCR - Desktop Wallet For Decred</h2>
```suggestion
        <h2 >GoDCR - Decred Wallet for Desktop</h2>
```

2022-05-23 18:08 UTC, dreacot approved these changes

2022-05-23 18:09 UTC, merged